artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/aasawari5/Text-Summarizer/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion_data.zip
  unzip_dir: artifacts/data_ingestion

